### ISSUE TITLE
Create a plan of the whole project

### ISSUE THREAD

**Issue by OlgaWa** [OlgaWa/cosmetic-ingredients-project#15]
1. Find a right dataset - DONE.
2. Create a zip folder with datasets on Drive - DONE.
3. Clean the data (to get only the data needed for the project) - DONE.
4. Create another zip folder with cleaned datasets on Drive - DONE.
5. Make a description of the project (what the program/app is going to do) - DONE.
6. Create a database and create tables - DONE.
7. Add data from the pdfs to the database - DONE.
8. Write a code that returns information about one cosmetic ingredient - DONE.
9. Write a code that returns information about functions of cosmetic ingredients - DONE.
10. Write a code that returns infromation about cosmetic ingredients abbreviations - DONE.
11. Write a code that returns a list of cosmetic ingredients from a specific group or connected to a specific ingredient (for example PEG-s, oils, plant extracts, strawberry, centella etc.) - DONE.
12. Write a code that generates PDF with the cosmetic ingredients / functions etc. that the user searched - DONE.
13. Create a Web App with Cosmetic Ingredients Project - DONE.
14. Deploy the app - DONE.
15. Write readme - DONE.

**Comment by OlgaWa** [comment]
Hello! @mocking-mike , @luwso - what do you think?

**Comment by mocking-mike** [comment]
Great plan, we can make a really good product from all these information!
